#!/bin/bash

declare -i true=0
declare -i false=1

declare outputDir="/home/$USER/special-backup"
declare -a backupSources=("boot" "etc" "home" "root" "srv" "usr" "var")
declare -a noBackupSources=("var/cache" "var/run" "var/tmp" "home/lost+found" "${outputDir:1}")

main(){
	cd /
	archiveType="tar.gz"

	for i in "${backupSources[@]}"; do
		Scan "0" "$i"
		cd /
	done
}

Scan(){
	local tabCount=$1; shift
	local i="$*"

	EchoTabs "$tabCount"; echo -n "Scanning: "
	if [[ "$PWD" == "/" ]]; then
		echo "\"$PWD$i\""
		i="$PWD$i"
	else
		echo "\"$PWD/$i\""
		i="$PWD/$i"
	fi

	if (( $(sudo du -sb "$i" | awk '{print $1}') > $((5 * (2**30) -1)) )); then

		#Check if file or directory
		if [[ -f "$i" ]]; then
			Backup "$i"
			return
		fi

		if [[ "$i" == "/root" ]]; then
			Backup "$i"
		fi

		#Must be a directory
		#Step into
		cd "$i" || exit

		# shellcheck disable=SC2207
		local curdirSubdirs=($(sudo ls -a))

		for j in "${curdirSubdirs[@]}"; do
			if [[ "$j" == "." ]] || [[ "$j" == ".." ]]; then continue; fi
			
			Scan $((tabCount+1)) "$j"
			cd "$i" || exit

		done
	else
		Backup "$tabCount" "$i"
	fi
}

Backup(){
	local tabCount=$1; shift
	local i="$*"

	if WriteOrNot "$i"; then
		local exclude=""
		local dirName="$(dirname "$i")"

		if [[ "$i" == "/var" ]]; then
			echo -n "Excluding: "
			for j in "${noBackupSources[@]}"; do
				# shellcheck disable=SC2140
				exclude+="--exclude="\'"/$j"\'" "
				# shellcheck disable=SC2140
				echo -ne \'"$j"\'" "
			done
			echo -ne "\n"
		fi
		
		EchoTabs "$tabCount"; echo "Backing up: \"$i\""

		if [[ -f "$outputDir$i.$archiveType" ]]; then
			echo "WARNING: RM ENVOKED [ph]"
			#sudo rm "$outputDir$i.$archiveType"
		fi

		if [[ "$dirName" != "/" ]]; then
			mkdir "$outputDir$dirName" 2> /dev/null
		fi

	#	echo -e "tar $exclude-cf - $i -P | xz -z -9e -T0 > $outputDir$i.tar.xz"
		sudo tar "$exclude" -cf - "$i" -P | sudo gz -v --best -c > "$outputDir$i.$archiveType"

		EchoTabs "$tabCount"; echo "Backed complete"
	else
		EchoTabs "$tabCount"; echo "Backup unnecessary, Skipping: \"$i\""
	fi
}

WriteOrNot(){
	local checkSource="$*"

	if [[ ! -f "$checkSource$archiveType" ]]; then return $true; fi

	local fileTime; fileTime="$(date -r "$checkSource" "+%Y%m%d%H%M%S")"
	local archiveTime; archiveTime="$(date -r "$outputDir$checkSource.$archiveType" "+%Y%m%d%H%M%S")"

	if (( fileTime > archiveTime )); then
		return $true
	else
		return $false
	fi
}

CheckSudo(){
	if [[ "$(whoami)" != "root" ]]; then
		echo "Not run as root, checking sudo privileges"
		if [[ "$(sudo whoami)" != "root" ]]; then
			echo "Error: requires sudo privileges"
			return $false
		else
			echo -e "Privileges verified\n"
			return $true
		fi
	fi
	return $true
}

EchoTabs(){
	local num=$1
	for ((p=0; p<num; p++)); do
		echo -ne "\t"
	done
}

CheckSudo; main; exit